#!/bin/sh
# chkconfig: 2345 95 20
# description: auto restore iptables rules
# restore iptables rules from /etc/sysconfig/iptables
# processname: pfw

PROGRAM=/usr/sbin/iptables

FIREWALL=`/bin/basename $PROGRAM`
RULES_FILE=/etc/sysconfig/${FIREWALL}
LOADER=${PROGRAM}-restore

if [ ! -f ${RULES_FILE} ]
then
	echo "$0: Cannot find ${RULES_FILE}"
	exit 1
fi

case "$1" in
	start)
		${LOADER} < ${RULES_FILE} || exit 1
		;;
	stop)
		${PROGRAM} -F
		${PROGRAM} -X
		;;

	*)
		echo "Usage: $0 start|stop"
		exit 1
		;;
esac
